# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Thousand under' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Required by RNFirebase
    pod 'Firebase/Core', '~> 6.8.1'

  # Pods for motorsReactApp
  pod 'Firebase/AdMob', '~> 6.8.1'
  pod 'Firebase/Analytics', '~> 6.8.1'
  pod 'Firebase/Database', '~> 6.8.1'
  pod 'Firebase/Messaging', '~> 6.8.1'






pod 'Thousand underTests', :path => '../node_modules/react-native-webview'

  

  target 'Thousand underTests' do
    inherit! :search_paths
    # Pods for testing



    pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  end

end

post_install do |installer|
  find_and_replace("../node_modules/react-native/React/CxxBridge/RCTCxxBridge.mm",
    "_initializeModules:(NSArray<id<RCTBridgeModule>> *)modules", "_initializeModules:(NSArray<Class> *)modules")
      installer.pods_project.targets.each do |target|
           target.build_configurations.each do |config|
                config.build_settings['CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF'] = 'NO'
           end
      end
 end

 

 def find_and_replace(dir, findstr, replacestr)
  Dir[dir].each do |name|
      text = File.read(name)
      replace = text.gsub(findstr,replacestr)
      if text != replace
          puts "Fix: " + name
          File.open(name, "w") { |file| file.puts replace }
          STDOUT.flush
      end
  end
  Dir[dir + '*/'].each(&method(:find_and_replace))
end


react_project = Xcodeproj::Project.open("../node_modules/react-native/React/React.xcodeproj")
    react_project.main_group["React/Views"].files.each do |file|   
      if file.path.match(/^RCTWebView/) 
        file.remove_from_project
      end   
    end   
react_project.save